terraform-docs:
  stage: quality
  image:
    name: quay.io/terraform-docs/terraform-docs:0.24.0-amd64
    entrypoint: [""]
  script:
    - |
      if [ -f tfdocs.yml ]; then
        echo "Using existing tfdocs.yml from the repository"
      else
        echo "tfdocs.yml not found, generating default configuration"
        echo -e "formatter:\"markdown table\"" > tfdocs.yml
        echo "output:" >> tfdocs.yml
        echo -e "  file:\"README.md\"" >> tfdocs.yml
        echo -e "  mode:inject" >> tfdocs.yml
        echo -e "  template:|-" >> tfdocs.yml
        echo "    <!-- BEGINNING OF PRE-COMMIT-TERRAFORM DOCS HOOK -->" >> tfdocs.yml
        echo "    {{ .Content }}" >> tfdocs.yml
        echo "    <!-- END OF PRE-COMMIT-TERRAFORM DOCS HOOK -->" >> tfdocs.yml
      fi
    - terraform-docs version
    - terraform-docs markdown --config tfdocs.yml --output-file README.md --output-check .