variables:
  TF_TFSEC_IMAGE: "aquasec/tfsec-ci"
  TF_TFSEC_VERSION: "v1.28.1"

terraform-tfsec:
  stage: quality
  variables:
    OUTPUT: tfsec.xml
  image:
    name: ${TF_TFSEC_IMAGE}:${TF_TFSEC_VERSION}
  script:
    - tfsec . --format junit --out ${OUTPUT} --config-file=.tfsec.yml --var-file tests/terraform.tfvars
  after_script:
    - cat ${OUTPUT}
  artifacts:
    name: "$CI_JOB_NAME artifacts from $CI_PROJECT_NAME on $CI_COMMIT_REF_SLUG"
    reports:
      junit:
        - ${OUTPUT}
