variables:
  TF_TFLINT_IMAGE: "ghcr.io/terraform-linters/tflint-bundle"
  TF_TFLINT_VERSION: v0.45.0.2

terraform-tflint:
  stage: quality
  variables:
    OUTPUT: tflint.xml
  image:
    name: ${TF_TFLINT_IMAGE}:${TF_TFLINT_VERSION}
    entrypoint: [""]
  script:
    - tflint --init
    - tflint --config .tflint.hcl -f junit > ${OUTPUT}
  after_script:
    - cat ${OUTPUT}
  artifacts:
    name: "$CI_JOB_NAME artifacts from $CI_PROJECT_NAME on $CI_COMMIT_REF_SLUG"
    reports:
      junit: ${OUTPUT}
