include:
  - local: /templates/base/.gitlab-ci.basic-semantic-release.yml

# DRYRUN EXECUTION

semantic-release-dryrun:
  extends: .semantic-release-dryrun
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH'
    - if: '$SEMANTIC_RELEASE_DRYRUN_ON_DEFAULT_BRANCH == "true"'

# NORMAL EXECUTION

semantic-release:
  extends: .semantic-release
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
