terraform-docs:
  stage: quality
  image:
    name: cytopia/terraform-docs:0.16.0
  script:
    - echo -e "formatter:\x20\"markdown table\"" > tfdocs.yml
    - echo "output:" >> tfdocs.yml
    - echo -e "  file:\x20\"README.md\"" >> tfdocs.yml
    - echo -e "  mode:\x20inject" >> tfdocs.yml
    - echo -e "  template:\x20|-" >> tfdocs.yml
    - echo "    <!-- BEGINNING OF PRE-COMMIT-TERRAFORM DOCS HOOK -->" >> tfdocs.yml
    - echo "    {{ .Content }}" >> tfdocs.yml
    - echo "    <!-- END OF PRE-COMMIT-TERRAFORM DOCS HOOK -->" >> tfdocs.yml
    - terraform-docs --config tfdocs.yml --output-check .
