variables:
  TF_IMAGE: "hashicorp/terraform"
  TF_VERSION: "1.3.9"

terraform-fmt:
  stage: quality
  image:
    name: ${TF_IMAGE}:${TF_VERSION}
    entrypoint: [""]
  script:
    - terraform fmt -check -diff -recursive
