terraform-tflint:
  stage: quality
  variables:
    OUTPUT: tflint.xml
  image:
    name: ghcr.io/terraform-linters/tflint:v0.55.1
    entrypoint: [""]
  script:
    - tflint --init
    - tflint --config .tflint.hcl -f junit > ${OUTPUT}
  after_script:
    - cat ${OUTPUT}
  artifacts:
    name: "$CI_JOB_NAME artifacts from $CI_PROJECT_NAME on $CI_COMMIT_REF_SLUG"
    reports:
      junit: ${OUTPUT}
