stages:
    - quality
    - pre-release
    - release

include:
    - local: /templates/base/.gitlab-ci.gitleaks.yml
    - local: /templates/base/.gitlab-ci.tffmt.yml
    - local: /templates/base/.gitlab-ci.tflint.yml
    - local: /templates/base/.gitlab-ci.tfsec.yml
    - local: /templates/base/.gitlab-ci.tfdocs.yml
    - local: /templates/base/.gitlab-ci.basic-semantic-release-auto.yml
