stages:
    - quality
    - build
    - release

include:
    - local: /templates/base/.gitlab-ci.gitleaks.yml
    - local: /templates/base/.gitlab-ci.cookiecutter.yml
    - local: /templates/base/.gitlab-ci.basic-semantic-release-scheduled.yml
