stages:
    - quality
    - pre-release
    - release
    - build

variables:
    SEMANTIC_RELEASE_DRYRUN_ON_DEFAULT_BRANCH: "true"

include:
    - local: /templates/base/.gitlab-ci.gitleaks.yml
    - local: /templates/base/.gitlab-ci.basic-semantic-release-auto.yml
      rules:
          - if: $ENABLE_SEMANTIC_RELEASE != "false"
    - local: /templates/base/.gitlab-ci.docker-build-push.yml
