stages:
    - quality
    - pre-release
    - release
    - deploy

include:
    - local: /templates/base/.gitlab-ci.gitleaks.yml
    - local: /templates/base/.gitlab-ci.basic-semantic-release-scheduled.yml
