variables:
  # TFLINT
  TF_TFLINT_IMAGE: "ghcr.io/terraform-linters/tflint-bundle"
  TF_TFLINT_VERSION: v0.36.1.0

terraform-tflint:
  stage: lint
  tags:
    - lint
  image:
    name: ${TF_TFLINT_IMAGE}:${TF_TFLINT_VERSION}
    entrypoint: [""]
  before_script:
    - mkdir -p reports
    - chmod 777 reports
  script:
    - tflint --init --config .tflint.hcl --loglevel=debug
    - find infrastructure/ -type d -name "terraform" >> /tmp/list_files
    - |
      while read DIR; do
        REPORT=$(echo "${DIR}" | cut -d"/" -f2- | rev | cut -d"/" -f2- | rev | sed --expression "s/\//-/g")
        tflint --format junit --config .tflint.hcl "${DIR}" > reports/"${REPORT}"-tflint.xml || FAILED=true
      done < /tmp/list_files
    - if [ $FAILED ]; then exit 1; fi
  artifacts:
    name: "$CI_JOB_NAME artifacts from $CI_PROJECT_NAME on $CI_COMMIT_REF_SLUG"
    reports:
      junit: reports/*.xml
